name: Set Default Package Versions
description: 'Set default versions for CumulusCI and sfdx'
outputs:
  cumulusci-version: ${{ steps.store.outputs.cumulusci }}
  sfdx-version: $ {{ steps.store.outputs.sfdx }}
runs:
    using: "composite"
    steps:
      - name: Store Versions
        id: store
        run: |
          echo "::set-output name=cumulusci::3.61.1"
          echo "::set-output name=sfdx::7.154"
        shell: bash
